export const INCREMENT = "[COUNTER] INCREMENT"
export const DECREMENT = "[COUNTER] DECREMENT"
export const CLEAR = "[COUNTER] CLEAR"
export const CLEARSTR = "[RESULT] CLEARSTR"
export const ADD="[ADD] ADD"